<?php
require("connect.php");
global $dbh_online;
$dbh_online = new PDO('mysql:host=freakpants.ch;dbname=' . $dbname_online, $user_online, $password_online);

// select relevant fields for duplicate check
// SELECT `artistName`, `trackName`, `collectionName`, `collectionId`, `checked`, `correctCount`, `wildcardblocked`, `blockReason` FROM itunes_tracks WHERE

// tracks here are just marked as not for survival play
// they can still be put into playlists

$artists = [
    "Pop Magicians",
    "Harmony River",
    "Saxtribution",
    "Acoustic Heartstrings",
    "Sweet Little Band",
    "Cynthia Colombo",
    "Glee Cast",
    "Kimokawa",
    "White Knight Instrumental",
    "Keith Harrison",
    "Lisa Harris",
    "Rockabye Baby!",
    "Tiny Tracks",
    "Music Box Mania",
    "Molotov Cocktail Piano",
    "Midnite String Quartet",
    "The Piano Guys",
    "Silverlake String Quartet",
    "The Chillest",
    "Vitamin String Quartet",
    "8-Bit Arcade",
    "Workout",
    "Chris Margaritis",
    "Chill Sunset Cafe",
    "Sunday Night Piano Club",
    "Chiptune Punks",
    "Piano Dreamers",
    "Sundai Karaoke",
    "Piano Superstar",
    "The Remix DJ Boys",
    "The Gary Tesca Orchestra",
    "VDance",
    "Piano Skin",
    "Joyrides",
    "The Four Seasons",
    "Laurence Juber",
    "Ömür Göksel",
    "ProSound Karaoke Band",
    "Jason Chen",
    "The Killergroove Formula",
    "Pickin' On Series",
    "LadyGameLyric",
    "Juggernoud1 & Karliene",
    "Sandy Contrera",
    "Lionel Boisvert",
    "Smooth Jazz All Stars",
    "2CELLOS",
    "Sergio Presto",
    "The Innocent Men",
    "Matt Mardini",
    "MPBaby",
    "Girlfriend Material",
    "The Buddha Lounge Ensemble",
    "Straight No Chaser",
    "Christer Sjögren",
    "The Country Fiddle Players",
    "The Jazz Lounge Niki Band",
    "Will McMillan",
    "Loose Passenger Seat",
    "Mitch Snow",
    "Thecomputernerd01",
    "Mike Dawes",
    "FM Duo",
    "Shirtless Violinist",
    "Elijah Eilish",
    "Orgel Sound J-Pop",
    "Peter B.-Reber",
    "Max Bygraves",
    "The Butterfly Chillout Ensemble",
    "Christophe Rousset",
    "New Symphonic Orchestra",
    "Radio Heart",
    "Philharmonic",
    "Sherlock Holmes",
    "Piano Cover",
    "The Coverband",
    "8 Bit Universe",
    "8-Bit Misfits",
    "Julverne",
    "Reverse Osmosis",
    "White Noise",
    "Brown Noise",
    "Wassalou",
    "Puppini Sisters",
    "Joey Gould",
    "The Headliners",
    "The Conet Project",
    "Orchestra",
    "Brass Band",
    "Allan Davies Singers",
    "Gone Country",
    "Quatuor Ébène",
    "Beatlegrass",
    "Happy Holidays",
    "Challenge of the Yukon",
    "Good Ol' American Boys",
    "Bo.Dà.",
    "James Galway",
    "Nicholas Frega",
    "Pink Martini",
    "Kyle Coleman",
    "Chloe Flower",
    "Balcony",
    "Ryver Marlee",
    "Traven Luc",
    "Staatsoper",
    "Black Dyke Band",
    "Jungwacht Blauring Schweiz",
    "Schwyzerörgeli",
    "Bernie and the Dancehall Shakers",
    "Sepp mit Stixi & Sonja",
    "Kummerbuben",
    "Stefan Roos",
    "Arthur Brügger",
    "Piano",
    "Farting Toilet Guy",
    "Bathtub Dogs",
    "String Quartet",
    "Plus Guest",
];

$collections = [
    "Piano",
    "The Loudmouths Perform",
    "Frosh Week",
    "Anthems",
    "Ibiza",
    // "Best Hits of",
    // "Best Of",
    // "Best Summer Album",
    // "(Best Remix)",
    // "Best Country Of",
    "Best",
    // "2021 Hits",
    // "10s Hits",
    // "Autumn Hits",
    // "Award Winning Hits",
    // "Best Hits of",
    // "Feel Good Hits",
    // "Disco Hits",
    // "Absolute Dance Hits",
    // "Hits de l'été",
    // "Hits 'N' Flips 1967-1970",
    // "Hair Salon Hits",
    // "Hits 2021",
    // "Hits Autumn",
    // "Pop Hits",
    // "Radio Vintage hits",
    // "Pop Megahits",
    // "Greatest Hits",
    // "Hits Of All Time",
    // "Internet Rap Hits",
    // "#1 Hits",
    // "Hits of the",
    // "10's UK Hits",
    // "Nostalgia Hits",
    // "Summer Hits",
    // "Bong Hits",
    // "Summer HITS",
    // "Smash Hits",
    // "Canadian Hits",
    "Hits",
    // "Throwback Party",
    // "Summer Party",
    // "Pool Party",
    // "Retro Party",
    // "Silvesterparty",
    // "Pop Party",
    // "Tik Tok Party",
    // "Slumber Party",
    // "Dance Party",
    // "Pride Party",
    // "Girls Party",
    "Party",
    "Wrap Up",
    "New Years Eve",
    "Autumn Chill",
    "Back to School",
    "Tik Tock",
    // "Breakup Songs",
    // "Clean Pop Songs",
    // "The Songs That Made Them Famous",
    // "the Songs of ",
    // "Songs to Listen to in the Shower",
    // "Songs of the",
    // "Irish Songs for Girls",
    // "Mother's Day Songs",
    // "Songs Without Words",
    // "Love Songs",
    // "15 Starke Songs",
    // "Songs for",
    // "Sad Songs",
    "Songs",
    "Sad",
    "Bops",
    "Celebrate Women",
    "Galentine's Day",
    "Hangover Brunch",
    "Silvester ",
    "Sex Life",
    "Nyårsfest",
    "New Year New Me",
    "Neujahr",
    "Lip Sync Assassin",
    "Like I Can",
    "Kids",
    "Karaoke",
    "I'm Ok Now",
    "I will survive",
    "i was far too scared to hit him",
    "Reader's Digest Music",
    "NYE 2021",
    "Modern Crooners",
    "Rieu Celebrates",
    "90s",
    "Ao Vivo",
    "Surf Music Chill",
    "80s Electro Classics",
    "Big Beat Miami",
    "Essential Pieces",
    "Viral Now",
    "Super 70'S",
    "Movie Themes",
    "Pure Running",
    "Summer Dance",
    "Hottest in Hip Hop",
    "Five Star USA Idols",
    "Jazz and Beatles",
    "Lofi Renditions",
    "Instrumental",
    "Christmas Classics",
    "A Festive Event",
    "Dance Remix Diamonds",
    "90's Dance",
    "(DJ Mix)",
    "Happy New Year",
    "Now That's What I Call",
    "The Music of",
    "The Essential",
    "The Classics",
    "Tour Edition",
    "Summer 2021",
    "80's Classics",
    "Roxette Vaults",
    "Dance Vault Mixes",
    "iTunes Festival",
    "The Sensational 60's",
    "Anniversary",
    "Made Famous",
    "Headbanging to",
    "Tailgate",
    "BBQ",
    "Girls In Love",
    "Acoustic",
    "Remembering the",
    "Coffeehouse Classics",
    "Collection",
    "100 Originals",
    "The Voice Performance",
    "Sings",
    "The Beatles Mix",
    "Album In The World",
    "20 #1’S: 00s",
    "Viral Rap",
    "Belaaks 2",
    "Let It Beatles",
    "Nippers 50's",
    "from \"The Sing-Off\"",
    "Picks On the Beatles",
    "Relaxing Acoustic Music",
    "Ultra Trance",
    "Voice of ",
    "Magic 70's",
    // "Pop Ballads",
    // "Love Ballads",
    // "Hit Ballads",
    // "Rock Ballads",
    "Ballads",
    "In the Style of ",
    "Gaming Music",
    "(Version originale",
    "Inesquecíveis de",
    "Brass Pearls",
    "Tracks",
    "Everybody Loves The Beatles",
    // "Summer Throwback",
    // "Throwback Bangers",
    "Throwback",
    "Bangers",
    "Oh! My Honey",
    "- Hit Mix",
     // "Songs to Listen to in the Shower",
    // "Shower Singing",
    // "Singing In The Shower",
    // "Shower Studio",
    "Shower",
    // "Beach Fever",
    // "Beach Days",
    "Beach",
    "Jazz Greats Meet",
    "Back To The 70's",
    "R&B Halloween",
    "Past Masters",
    "Skater Head",
    "Bass Sound Off U.S.A",
    // "Playlist for Gamers",
    // "Music for Gamers",
    "Gamers",
    "Gaming",
    // "Classical Playlist",
    // "Playlist for Gamers",
    "Playlist",
    "Hot Summer",
    "brings you breakfast",
    "Summer Chill",
    "Just Like Beatles",
    "So 10s",
    "- Hit Rewind",
    "Autumn 2021",
    "Boogie Oogie - Internacional",
    "Radio Ga Ga",
    "Good Feeling",
    "Discover More Soul",
    "Ambient Translations",
    "70's Top 40",
    "Collectors Series",
    "Meets the Beatles",
    "- Das Musical",
    "Fitness Motivation",
    "Turnt Up",
    "(Music From the Original Series)",
    "Basketball Finals",
    "Mother's Day Love",
    "Acoustic With",
    // "Summer Jams",
    // "Saturday Jams",
    "Jams",
    "TikTok Summer",
    "Valley of Dutch Heroes",
    "- Rap Chill",
    "Rainbow Days",
    "(Original Soundtrack Album)",
    "On The Beatles",
    "Music Is Universal",
    "(Italian Album)",
    "Country Music Month",
    "Country Classics",
    "(From the Original Motion Picture Soundtrack)",
    "Van Vibes",
    "Christmas",
    "20 #1's",
    "(Deluxe",
    "Puro Bailoteo",
    "Volve Finde",
    "- Hip Hop",
    "Sing-Along",
    "Re-Recorded",
    "Sleepover",
    "Number 1's",
    "Pride Music",
    "Jacuzzi Vibes",
    "Neljä tähteä 4",
    "Greatest Pieces",
    // "On A Road Trip",
    // "Summer Road Trip",
    "Road Trip",
    "Mis Favoritas",
    "I classici",
    "Soundtrack",
    "Lullaby Renditions",
    "Zima 2020",
    "Banjo",
    "New Year's Eve",
    "Edition",
    "No Autotune",
    "Dear Bro",
    "New Year's Day",
    "Shut Up Lets Dance",
    "Hit of",
    "Beach Sa Bahay",
    "Covers",
    "Ellen DeGeneres",
    "in style of",
    "One Hit Wonders",
    "Simptok",
    "20 Suosikkia",
    "Summer Vibes",
    "(The Original",
    // "live im",
    // "Live On",
    // "Live In",
    // "[Live]",
    // "Live on Stage",
    // "(Live",
    // "(Live)",
    // ": Live",
    // "Live At",
    // "Live Around the World",
    "Live",
    "Mixtape",
    "Get Hyped",
    "Homework Vibes",
    "Workout",
    "Gospel",
    "Rap Favorites",
    "Remixes",
    "Just House",
    "Dialogue",
    "The Ultimate",
    "Remastered",
    "Band Concert",
    "Tributo",
    "Teenager Love",
    "Clásicos",
    "Fiesta en el balcón",
    "Version",
    "0s Explosion",
    "Sábado de",
    "Perreo",
    "Vol.",
    "Versions",
    "- Single",
    "Session",
    "Reprise",
    "Nominees",
    "Lockdown",
    "A State of Trance",
    "Singt",
    // ": Gold",
    // "Queen - This Is Gold",
    // "Golden Oldies",
    // "Platinum & Gold",
    // "70s Solid Gold",
    // "Pop Gold",
    "Gold",
    "Complete",
    "Shades of",
    "in famiglia",
    "Film",
    "Years of",
    "Re-Issue",
    "Charts",
    "Hot Girl Walk",
    "You Belong With Me",
    "Noel",
    "Lilo & Stitch",
    "Play the",
    "Gregorian",
    "Lonely Souls",
    "early days",
    "Daddy Cool",
    "in Dub",
    "Pregame",
    "Love Hurts",
    "For the Broken Hearted",
    "Disco Music",
    "Banda Sonora",
    "Encanto",
    "Remix Album",
    "Summer Mix",
    "Regaeton Bacan",
    "Soul Classics",
    // "Trending Pop",
    // "Trending Hip Hop",
    // "Trending Now",
    // "Trending Autumn",
    // "Indo Trending",
    "Trending",
    "Vivo",
    "Concierto",
    "Contest",
    "Compilation",
    "Yearbook",
    "10's",
    "10s",
    "Work From Home",
    "Translations",
    "Deluxe",
    "Summer Feeling",
    "in Person",
    "After Ski",
    "On the Radio",
    "Anti Social",
    "Spring Break",
    "Summer Joy",
    "Chill Zone",
    "Angst",
    "Girls Night",
    "Festival",
    "Headliner",
    "NDA",
    "GOOD BYE",
    "EURO",
    "Hot Girls",
    // "Fresh Pop",
    // "Pop for You",
    // "Pop 2K",
    // "Pop Royalty",
    // "- Pop",
    // "Pop Music",
    // "Pop Queens",
    // "Bubblebath Pop",
    // "- Dance Pop",
    // "Pop Tunes",
    // "Pop Sensations",
     // "Trending Pop",
    // "Pop Gold",
    // "Clean Pop Songs",
    // "Pop Party",
    // "Pop Megahits",
    // "Pop Hits",
    // "Pop from the Movies",
    // "Pop Divas",
    // "Pop Anthology",
    // "Soft Pop Beats",
    // "Punk Goes Pop",
    // "20 #1’s: Pop",
    // "0's Pop",
    // "Pop Alchemy",
    // "Shape of Pop",
    // "High Energy Pop",
    "Pop",
    "Hot & Viral",
    "Dancefloor",
    "Maniac",
    // "A Tribute to",
    // "Tribute to",
    // "Tribute:",
    "Tribute",
    // "Fiesta Latina",
    "Fiesta",
    "Cindo De Mayo",
    "per bambini",
    "Spanglish",
    "Hispanic",
    "Vibin",
    'dinero',
    "Latinx",
    "Heritage",    
    "No Parents",
    "festa",
    "Poppin",
    "scuola",
    "Viernes",
    "Nochecitas",
    "La vida es corta",
    "?????",
    "Reggaeton",
    "Bailar",
    "Finde",
    "Mix",
    "Edición",  
    "Aniversario",
    "Guitar",
    "Electronic Classics",
    "Rautavaara",
    "Hit Mix",
    "R&B Classics",
    "Rap Cutz",
    "el Ritmo",
    "Life Sucks",
    "Music for",
    "Feeling Good",
    "Take a Look at My Girlfriend",
    "Hip-Hop Summer",
    "#1's",
    "Rap Classics",
    "Quinceañera",
    "80s Sound",
    "urodzinowa",
    "impreza",
    "The Full Monty",
    "Disco Classics",
    "Musical",
    "Summer Cruisin",
    "A La Playa",
    "Re-Recording",
    "Jingle Bell",
    "Pure Emotions",
    "Balcony",
    "Relaxation",
    "Ambience",
    "Audio",
    "Medley",
    "Summer Heat",
    "Babies",
    "Tubes de",
    "Next Up: Dance",
    "Top 50",
    "Motivation",
    "Canciones",
    "Viral",
    "Run 2022",
    "Soft Dance",
    "Fitness",
    "Valentine",
    "Szilveszter",
    "Friday",
    "Year of the",
    "Duette",
    "Volume",
    "Discover More",
    "Play Date",
    "Greatest Summer",
    "TikTok",
    "Boost Your Mood",
    "Energy Booster",
    "Gaga Boob",
    "Songtrack",
    "California Vibes",
    "Too Sexy",
    "Jump Back In",
    "Originale",
    "Licence to Chill",
    "pov:",
    "Timeless R&B",
    "Head Bop",
    "Teenage Movie",
    "Timeless Hip-Hop",
    "Reckless Heart",
    "pink is a color",
    "IN DA CLUB",
    "lofi love",
    "NOBODY KNOWS",
    "Calm Summer Night",
    "Summertime",
    "Bikin",
    "Semangat",
    "Love Tonight",
    "RomanTic Tok",
    "Dance Classics",
    "Electronic Music",
    "Running",
    "die grossen Erfolge",
    "Blaze It",
    "Summer Vacation Vibes",
    "Kucna",
    "Žurka",
];

$tracks = ["Demo", "as made famous by", "Tribute To", "Acoustic", "Live", "Version", "Edited", "Medley", "Parody", "Christmas", "(From", "Tribute", "Dialogue"];

$collectionIds = [1591132006, 1441159224, 1441145575, 1574157039, 1573479361, 1447401519, 1462542595];

foreach ($artists as $artist) {
    echo $artist . '<br>';
    $sql = "UPDATE itunes_tracks SET wildcardBlocked = 1, blockReason = CONCAT('artist contains: ', :artist) WHERE artistName LIKE CONCAT('%', :artist, '%') AND checked != 1";
    $sth = $dbh_online->prepare($sql);
    $sth->execute(array(
        ":artist" => $artist,
    ));
}

foreach ($collections as $collection) {
    echo $collection . '<br>';
    $sql = "UPDATE itunes_tracks SET wildcardBlocked = 1, blockReason = CONCAT('collectionName contains: ', :collection) WHERE collectionName LIKE CONCAT('%', :collection, '%') AND checked != 1";
    $sth = $dbh_online->prepare($sql);
    $sth->execute(array(
        ":collection" => $collection,
    ));
}

foreach ($tracks as $track) {
    echo $track . '<br>';
    $sql = "UPDATE itunes_tracks SET wildcardBlocked = 1, blockReason = CONCAT('track contains: ', :track) WHERE trackName LIKE CONCAT('%', :track, '%') AND checked != 1";
    $sth = $dbh_online->prepare($sql);
    $sth->execute(array(
        ":track" => $track,
    ));
}

foreach ($collectionIds as $id) {
    echo $id . '<br>';
    $sql = "UPDATE itunes_tracks SET wildcardBlocked = 1, blockReason = CONCAT('collectionId: ', :id) WHERE collectionId = :id AND checked != 1";
    $sth = $dbh_online->prepare($sql);
    $sth->execute(array(
        ":id" => $id,
    ));
}

// select all checked tracks
$sql = "SELECT artistName, trackName FROM itunes_tracks WHERE checked = 1";
$sth = $dbh_online->prepare($sql);
$sth->execute();
$checkeds = $sth->fetchAll(PDO::FETCH_ASSOC);

foreach($checkeds as $checked) {
    echo $checked['artistName'] . ' - ' . $checked['trackName'] . '<br>';
    // dont overwrite previous reasons
    $sql = "UPDATE itunes_tracks SET wildcardBlocked = 1, blockReason = 'duplicate' WHERE artistName = :artistName AND trackName = :trackName AND checked != 1 AND wildcardBlocked != 1";
    $sth = $dbh_online->prepare($sql);
    $sth->execute(array(
        ":artistName" => $checked['artistName'],
        ":trackName" => $checked['trackName'],
    ));
}