<?php
require("connect.php");
global $dbh_online;
$dbh_online = new PDO('mysql:host=freakpants.ch;dbname=' . $dbname_online , $user_online, $password_online);

// tracks here are just marked as not for survival play
// they can still be put into playlists

$artists = [
    "Pop Magicians",
    "Harmony River",
    "Saxtribution",
    "Acoustic Heartstrings",
    "Sweet Little Band",
    "Cynthia Colombo",
    "Glee Cast",
    "Kimokawa",
    "White Knight Instrumental",
    "Keith Harrison",
    "Lisa Harris",
    "Rockabye Baby!",
    "Tiny Tracks",
    "Music Box Mania",
    "Molotov Cocktail Piano",
    "Midnite String Quartet",
    "The Piano Guys",
    "Silverlake String Quartet",
    "The Chillest",
    "Vitamin String Quartet",
    "8-Bit Arcade",
    "Power Music Workout",
    "Chris Margaritis",
    "Chill Sunset Cafe",
    "Sunday Night Piano Club",
    "Workout Remix Factory",
    "Workout Music",
    "Chiptune Punks",
    "Piano Dreamers",
    "Sundai Karaoke",
    "Piano Superstar",
    "The Remix DJ Boys",
    "The Gary Tesca Orchestra",
    "VDance",
    "Piano Skin",
    "Joyrides",
    "The Four Seasons",
    "Laurence Juber",
    "Ömür Göksel",
    "ProSound Karaoke Band",
    "Jason Chen",
    "The Killergroove Formula",
    "Pickin' On Series",
    "LadyGameLyric",
    "Juggernoud1 & Karliene",
    "Sandy Contrera",
    "Lionel Boisvert",
    "Smooth Jazz All Stars",
    "2CELLOS",
    "Sergio Presto",
    "The Innocent Men",
    "Matt Mardini",
    "MPBaby",
    "Girlfriend Material",
    "The Buddha Lounge Ensemble",
    "Straight No Chaser",
    "Christer Sjögren",
    "The Country Fiddle Players",
    "The Jazz Lounge Niki Band",
    "Will McMillan",
    "Loose Passenger Seat",
    "Mitch Snow",
];

$collections = [
"10s Hits",
"Piano Covers, Vol. 5",
"The Loudmouths Perform",
"Frosh Week",
"2021 Hits",
"Throwback Party",
"Wrap Up",
"New Years Eve",
"Autumn Chill",
"Autumn Hits",
"Award Winning Hits",
"Back to School",
"Best Hits of",
"Tik Tock",
"Breakup Songs",
"Celebrate Women",
"Galentine's Day",
"Hair Salon Hits",
"Hangover Brunch",
"Hits 2021",
"Hits Autumn",
"Silvesterparty",
"Silvester ",
"Sex Life",
"Pop Party",
"Pop Hits",
"Nyårsfest",
"New Year New Me",
"Neujahr",
"Lip Sync Assassin",
"Like I Can",
"Kids R Us",
"I'm Ok Now",
"I will survive",
"i was far too scared to hit him",
"Reader's Digest Music",
"Big Workout Hits",
"A Tribute to",
"The Very Best Of",
"NYE 2021",
"Modern Crooners",
"Hit Ballads",
"Trending Autumn",
"Piano Covers",
"Rieu Celebrates",
"(Live)",
"The Ultimate Fan Extras Collection",
"'90s Soul Number 1's",
"Hits 'N' Flips 1967-1970",
"Ao Vivo",
"Surf Music Chill",
"Trending Now",
"Best of the 60'S",
"80s Electro Classics",
"Pop Megahits",
"Greatest Hits",
"Absolutely The Best Of",
"Big Beat Miami",
"Radio Vintage hits",
"Clean Pop Songs",
"The Songs That Made Them Famous",
"Essential Pieces",
": Live",
"Viral Now",
"Super 70'S",
"Movie Themes",
"Pure Running",
"Hits Of All Time",
"Summer Dance Pop",
"Platinum & Gold",
"Hottest in Hip Hop",
"Five Star USA Idols",
"Pop Sensations",
"Jazz and Beatles",
"Lofi Renditions",
"Instrumental Covers",
"Christmas Classics",
"A Festive Event",
"Hits de l'été",
"Love Ballads",
"Dance Remix Diamonds",
"Internet Rap Hits",
"Retro Party",
"90's Dance",
"(DJ Mix)",
"Happy New Year",
"Cover Songs Instrumental",
"70s Solid Gold",
"Now That's What I Call",
"Tik Tok Party",
"#1 Club Hits",
"Tribute to",
"The Music of",
"Hits of the",
"The Essential",
"The Classics",
"Tour Edition",
"Pop Divas",
"Summer 2021",
"2000s Love Songs",
"(Live",
"Slumber Party",
"80's Classics",
"Roxette Vaults",
"Dance Vault Mixes",
"Dance Party",
"Live At",
"iTunes Festival",
"The Best of ",
"10's UK Hits",
"The Sensational 60's",
"Anniversary (Box Set)",
"Pride Party",
"Made Famous",
"Headbanging to",
"the Songs of ",
"Tailgate Hits",
"Nostalgia Hits",
"Girls In Love",
"Songs to Listen to in the Shower",
"Pop Tunes",
"(Acoustic Version)",
"Songs For Kids",
"Remembering the",
"Trending Hip Hop",
"Coffeehouse Classics",
"Live Around the World",
"The Greatest 90s Soul",
"Pop Anthology",
"Songs of the",
"80's the Collection",
"Bong Hits",
"(Best Remix)",
"100 Originals",
"Summer Hits",
"Pool Party",
"Hits On Piano",
"Pop from the Movies",
"The Voice Performance",
"Sings The Beatles",
"The Beatles Mix",
"Best Summer Album",
"Album In The World",
"20 #1’S: 00s",
"Viral Rap",
"Best Country Of",
"Soft Pop Beats",
"Best of Village People",
"Girls Party",
"Belaaks 2",
"Let It Beatles",
"Nippers 50's",
"from \"The Sing-Off\"",
"Summer HITS",
"Picks On the Beatles",
"Relaxing Acoustic Music",
"Ultra Trance",
"Relaxing Instrumentals",
"- Dance Pop",
"Voice of ",
"Magic 70's",
"Pop Ballads",
"In the Style of ",
"Gaming Music",
"Instrumental Karaoke",
"Tribute:",
"(Version originale",
];

$tracks = ["Demo)", "as made famous by", "Tribute To", "(Acoustic Version)"];

foreach($artists as $artist){
    echo $artist . '<br>';
    $sql = "UPDATE itunes_tracks SET wildcardBlocked = 1 WHERE artistName LIKE CONCAT('%', :artist, '%')";
    $sth = $dbh_online->prepare($sql);
    $sth->execute(array(
        ":artist" => $artist,
    ));
}

foreach($collections as $collection){
    echo $collection. '<br>';
    $sql = "UPDATE itunes_tracks SET wildcardBlocked = 1 WHERE collectionName LIKE CONCAT('%', :collection, '%')";
    $sth = $dbh_online->prepare($sql);
    $sth->execute(array(
        ":collection" => $collection,
    ));
}

foreach($tracks as $track){
    echo $track. '<br>';
    $sql = "UPDATE itunes_tracks SET wildcardBlocked = 1 WHERE trackName LIKE CONCAT('%', :track, '%')";
    $sth = $dbh_online->prepare($sql);
    $sth->execute(array(
        ":track" => $track,
    ));
}


?>